// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnyxxagqtseounwdbsfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRueXh4YWdxdHNlb3Vud2Ric2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3NzA3OTQsImV4cCI6MjA4NjM0Njc5NH0.dClQF3FFDkTOyQz5BCZ_8XEYQZYOm7t7fyF50Pioluk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});